version: '3'
services:
  orders:
    build:
      context: .
      dockerfile: ./apps/orders/Dockerfile
      target: development
    command: npm run start:dev orders
    env_file:
      - ./apps/billing/.env
    depends_on:
      - mongo
      - billing
      - rabbitmq
      # - mongodb-primary
      # - mongodb-secondary
      # - mongodb-arbiter
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    ports:
      - 3000:3000
    # networks:
    #   - rabbitmq_go_net

  billing:
    build:
      context: .
      dockerfile: ./apps/billing/Dockerfile
      target: development
    command: npm run start:dev billing
    env_file:
      - ./apps/billing/.env
    depends_on:
      - mongo
      - rabbitmq
      # - mongodb-primary
      # - mongodb-secondary
      # - mongodb-arbiter
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    # networks:
    #   - rabbitmq_go_net

  rabbitmq:
    image: rabbitmq
    ports:
      - 5672:5672
      # - 15672:15672
    # volumes:
    #   - ~/.docker-conf/rabbitmq/data/:/var/lib/rabbitmq/
    #   - ~/.docker-conf/rabbitmq/log/:/var/log/rabbitmq
    # networks:
    #   - rabbitmq_go_net

  mongo:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: password123
    # networks:
    #   - rabbitmq_go_net
# networks:
#   rabbitmq_go_net:
#     driver: bridge

# mongodb-primary:
#   image: docker.io/bitnami/mongodb:5.0
#   restart: always
#   environment:
# - MONGODB_ADVERTISED_HOSTNAME=mongodb-primary
# - MONGODB_REPLICA_SET_MODE=primary
# - MONGODB_ROOT_USER=root
# - MONGODB_ROOT_PASSWORD=password123
# - MONGODB_REPLICA_SET_KEY=replicasetkey123
#   volumes:
#     - 'mongodb_master_data:/bitnami/mongodb'
#   ports:
#     - '27017:27017'

# mongodb-secondary:
#   image: docker.io/bitnami/mongodb:5.0
#   depends_on:
#     - mongodb-primary
#   environment:
#     - MONGODB_ADVERTISED_HOSTNAME=mongodb-secondary
#     - MONGODB_REPLICA_SET_MODE=secondary
#     - MONGODB_INITIAL_PRIMARY_HOST=mongodb-primary
#     - MONGODB_INITIAL_PRIMARY_ROOT_PASSWORD=password123
#     - MONGODB_REPLICA_SET_KEY=replicasetkey123

# mongodb-arbiter:
#   image: docker.io/bitnami/mongodb:5.0
#   depends_on:
#     - mongodb-primary
#   environment:
#     - MONGODB_ADVERTISED_HOSTNAME=mongodb-arbiter
#     - MONGODB_REPLICA_SET_MODE=arbiter
#     - MONGODB_INITIAL_PRIMARY_HOST=mongodb-primary
#     - MONGODB_INITIAL_PRIMARY_ROOT_PASSWORD=password123
#     - MONGODB_REPLICA_SET_KEY=replicasetkey123
# volumes:
#   mongodb_master_data:
#     driver: local

